name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: тест even/odd
      run: |
        chmod +x ./fgun4ik_test.sh
        ./fgun4ik_test.sh
