name: Тестирование

on:
  push:
    branches:
      - main  # ветка, на которой запускаются тесты

jobs:
  test:
    runs-on: ubuntu-latest  # Операционная система для выполнения тестов

    steps:
    - name: Проверка кода
      uses: actions/checkout@v2  # Клонирование репозитория

    - name: Установка зависимостей
      run: |
        chmod +x fgxn4ik_AS.sh
        npm install  # Пример установки зависимостей

    - name: Запуск тестов
      run: |
        ./fgxn4ik_AS.sh
        if [[ $? -eq 1 ]]; then
            echo "Тест №1 пройден!"
        else
            echo "Тест №1 провален :("
            echo "Входные аргументы: ПУСТО"
            exit 1
        fi

        ./fgxn4ik_AS.sh "$input_file" "$output_file" -d четные
        if [[ $? -eq 0 ]]; then
            echo "Тест №2 пройден!"
        else
            echo "Тест №2 провален :("
            echo "Входные аргументы: $input_file $output_file -d четные"
            exit 1
        fi

        ./fgxn4ik_AS.sh "$input_file" "$output_file" -d неправильное
        if [[ $? -eq 1 ]]; then
            echo "Тест №3 пройден!"
        else
            echo "Тест №3 провален :("
            echo "Входные аргументы: $input_file $output_file -d неправильное"
            exit 1
        fi

        result=$(cat "$output_file")
        expected_result=4
        if [[ $result -eq $expected_result ]]; then
            echo "Результат верный."
        else
            echo "Результат неверный :("
            echo "Ожидаемый результат: $expected_result"
            echo "Фактический результат: $result"
            exit 1
        fi

        echo "Все тесты пройдены успешно!"
